version: '3'

services:
  jupyter:
    build: .
    command: jupyter-notebook --ip="0.0.0.0" --no-browser --allow-root --NotebookApp.token= --NotebookApp.notebook_dir="/usr/src/app/notebooks" --NotebookApp.port=8888
    ports:
      - 8893:8888
    volumes:
      - .:/usr/src/app
    restart: "no"
    working_dir: /usr/src/app